[book]
authors = ["ManeraKai"]
language = "en"
multilingual = false
src = "src"
title = "College Resources"

[output.html]
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0