[book]
authors = ["ManeraKai"]
language = "en"
multilingual = false
src = "src"
title = "College Resources"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ManeraKai/college-resources"
additional-css = ["src/custom.css"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0